[actions] attempt to install cmake via brew now causes build failures.
```
Run brew install cmake doxygen ninja graphviz lilv gettext
Error: cmake was installed from the local/pinned tap
but you are trying to install it from the homebrew/core tap.
Formulae with the same name from different taps cannot be installed at the same time.

To install this version, you must first uninstall the existing formula:
  brew uninstall cmake
Then you can install the desired version:
  brew install cmake
```